### PR TITLE
Show total specificity

### PR DESCRIPTION
**Pull request by vegerot**
After spending 45 minutes trying to get `node-sass` to compile on my MacBook, I gave up and looked for an alternative to `webpack-config-vue` (that bundles a version of `node-sass` from a few years ago).  The simplest solution was switching to `vue-cli`, which gives you the option of specifying `node-sass` or `sass`.

My intention for the PR was not to switch to `vue-cli`, but I needed to in order to run the dev server.

### CODE REVIEW

**Comment by keeganstreet** [comment]
Hi Max, thanks for your contribution. I would be happy to merge the migration to vue-cli. I would just have some very minor comments to add about that.

However, I'm not so sure about the "total specificity" which was the main reason for your PR. A classname selector is not a 10x multiple of an element selector, and an ID selector is not a 10x multiple of a classname selector. Your change would suggest that a selector of `.a.b.c.d.e.f.g.h.i.j.k` (11 classnames) has a higher specificity than `#id`, which is not correct. Does that make sense?

**Comment by vegerot** [comment]
@keeganstreet interesting.  I used your website while going through the [Specificity](https://web.dev/learn/css/specificity/#scoring-each-selector-type) lesson on web.dev .  Is this section mistaken, then?

**Comment by keeganstreet** [comment]
@vegerot yeah that sections not technically correct. They have made a simplification which makes it easier to grasp the fundamental idea of specificity, but their model breaks with long selectors. In reality, it would be very unlikely to use a CSS selector with more than 10 parts, which would be the justification for this simplification. But I would prefer to err on the side of correctness than simplicity for this.

**Comment by vegerot** [comment]
I didn't realize this.  If you would like to correct this, since there's many people taking this as a source of truth, you can edit the page [here](https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/learn/css/specificity/index.md).  Anyways, thanks!

/close

**Pull request closed without merging**
